# Generated by Django 5.2.6 on 2025-09-04 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_rayon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('idCont', models.AutoField(primary_key=True, serialize=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rayons', to='monApp.produit')),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='monApp.rayon')),
            ],
        ),
    ]
