# Generated by Django 5.2.6 on 2025-09-09 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_contenir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenir',
            name='idCont',
        ),
        migrations.AddField(
            model_name='contenir',
            name='pk',
            field=models.CompositePrimaryKey('produit', 'rayon', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='contenir',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contenir',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monApp.produit'),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='rayon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monApp.rayon'),
        ),
    ]
