# Generated by Django 5.2.6 on 2025-09-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0004_remove_contenir_idcont_contenir_pk_contenir_quantite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_fabrication',
            field=models.DateField(blank=True, null=True),
        ),
    ]
