# Generated by Django 5.2.6 on 2025-10-09 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0007_produit_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='rayons',
            field=models.ManyToManyField(related_name='produits', through='monApp.Contenir', to='monApp.rayon'),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='rayon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenir_rayon', to='monApp.rayon'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit', to='monApp.statut'),
        ),
    ]
